Add `.detach()` in `scalar_to_float()` (#551)
Summary:
Pull Request resolved: https://github.com/pytorch/tnt/pull/551

Calling from an integration test with full training loop that used in mem logger was throwing this exception:
```
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

This diff adds the `.detach()`

Reviewed By: JKSenthil

Differential Revision: D49600572

fbshipit-source-id: 996d5216612fe741a078c8b5fea94b76e7a5c84e