Fix module to device in AutoUnit (#398)
Summary:
Pull Request resolved: https://github.com/pytorch/tnt/pull/398

In D46001765 the `self.device` reference was accidentally changed to `device`. Because of this the module isn't being moved to the device properly and we are seeing errors like:
```
ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [1], output_device None, and module parameters {device(type='cpu')}
```
when running vise DDP.

Reviewed By: bobakfb

Differential Revision: D46056924

fbshipit-source-id: d980909fa745161a800c72d91d849ee04b27aea7