Update torchtnt for Python 3.12 (#964)
Summary:
Pull Request resolved: https://github.com/pytorch/tnt/pull/964

In Python 3.12, dataclass field defaults must be immutable, and implementing a custom `__eq__` on the enum will cause an error like:
```
ValueError: mutable default <enum 'StoppingMechanism'> for field stopping_mechanism is not allowed: use default_factory
```

To work around this, we can inherit from `StrEnum` (newly added into Python 3.12) which supports direct `==` comparisons against strings. For backwards compatibility, we define our own version of it as well.

Reviewed By: diego-urgell

Differential Revision: D68466161

fbshipit-source-id: 1c831cb4449adc953d921ee3559616d5c7b00f86