Fix progress esitmation with no len support (#606)
Summary:
Pull Request resolved: https://github.com/pytorch/tnt/pull/606

When dataset does not implement __len__, it is actually throwing TypeError which is not being caught.
This diff fixes that

Reviewed By: ninginthecloud

Differential Revision: D50886583

fbshipit-source-id: 63d2fdd47a449cb540f30fbdd5b401e9c653e3e7