Explicit none checks for progress bar callback (#258)
Summary:
Pull Request resolved: https://github.com/pytorch/tnt/pull/258

Follow up to comment on https://github.com/pytorch/tnt/pull/223
Stack trace when run with `max_steps` and `max_steps_per_epoch` both set to None

```
torchtnt/runner/callbacks/tqdm_progress_bar.py in on_train_step_end(self, state, unit)
     43
     44     def on_train_step_end(self, state: State, unit: TTrainUnit) -> None:
---> 45         if self._train_progress_bar and state.train_state:
     46             _update_progress_bar(
     47                 self._train_progress_bar,
tqdm/std.py in __bool__(self)
   1118             return self.total > 0
   1119         if self.iterable is None:
-> 1120             raise TypeError('bool() undefined when iterable == total == None')
   1121         return bool(self.iterable)
   1122
TypeError: bool() undefined when iterable == total == None
```

Reviewed By: JKSenthil

Differential Revision: D40643481

fbshipit-source-id: 03293c13c7e7b0cc9940169808ef2d525ce920a5