remove optional comment in docstring for step (#482)
Summary:
Pull Request resolved: https://github.com/pytorch/tnt/pull/482

received this error:

```
[0]: > self.tb_logger.log("avg_test_auc", self.total_auc_sum / self.num_eval_steps)
[0]:TypeError: TensorBoardLogger.log() missing 1 required positional argument: 'step'
```

Docstring says it is optional, but it is typed to be enforced. Removing `optional` from docstring

Differential Revision: D47921178

fbshipit-source-id: c6be8070f0d7752242bc8c700b0f8ee652b298b1