Fix module to device in AutoUnit
Summary:
In D46001765 the `self.device` reference was accidentally changed to `device`. Because of this the module isn't being moved to the device properly and we are seeing errors like:
```
ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [1], output_device None, and module parameters {device(type='cpu')}
```
when running vise DDP.

Differential Revision: D46056924

fbshipit-source-id: ce22d1efb542b57b951430f0c75d6b075b0e956e