Add `.detach()` in `scalar_to_float()`
Summary:
Calling from an integration test with full training loop that used in mem logger was throwing this exception:
```
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

This diff adds the `.detach()`

Reviewed By: JKSenthil

Differential Revision: D49600572