Fix progress esitmation with no len support
Summary:
When dataset does not implement __len__, it is actually throwing TypeError which is not being caught.
This diff fixes that

Reviewed By: ninginthecloud

Differential Revision: D50886583