Update torchtnt for Python 3.12
Summary:
In Python 3.12, dataclass field defaults must be immutable, and implementing a custom `__eq__` on the enum will cause an error like:
```
ValueError: mutable default <enum 'StoppingMechanism'> for field stopping_mechanism is not allowed: use default_factory
```

To work around this, we can inherit from `StrEnum` (newly added into Python 3.12) which supports direct `==` comparisons against strings. For backwards compatibility, we define our own version of it as well.

Reviewed By: diego-urgell

Differential Revision: D68466161